CREATE TABLE IF NOT EXISTS ORDEN (
  ordn_id INT NOT NULL,
  ordn_fecha DATE NULL,
  PLATO_plt_id   INT NOT NULL,
  MESERO_mes_id  INT NOT NULL,
  CLIENTE_cli_id INT NOT NULL,
  PRIMARY KEY (ordn_id, PLATO_plt_id, MESERO_mes_id),
  INDEX fk_ORDEN_PLATO1_idx (PLATO_plt_id ASC) VISIBLE,
  INDEX fk_ORDEN_MESERO1_idx (MESERO_mes_id ASC) VISIBLE,
  INDEX fk_ORDEN_CLIENTE1_idx (CLIENTE_cli_id ASC) VISIBLE,
  CONSTRAINT fk_ORDEN_PLATO1
    FOREIGN KEY (PLATO_plt_id)
    REFERENCES PLATO (plt_id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_ORDEN_MESERO1
    FOREIGN KEY (MESERO_mes_id)
    REFERENCES MESERO (mes_id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_ORDEN_CLIENTE1
    FOREIGN KEY (CLIENTE_cli_id)
    REFERENCES CLIENTE (cli_id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    );
