CREATE TABLE IF NOT EXISTS PLATO (
  plt_id INT NOT NULL,
  plt_nombre VARCHAR(200) NULL,
  plt_precio INT NULL,
  plt_descripcion VARCHAR(300) NULL,
  TIPO_PLATO_tp_plt_id INT NOT NULL,
  PRIMARY KEY (plt_id),
  INDEX fk_PLATO_TIPO_PLATO1_idx (TIPO_PLATO_tp_plt_id ASC) VISIBLE,
  CONSTRAINT fk_PLATO_TIPO_PLATO1
    FOREIGN KEY (TIPO_PLATO_tp_plt_id)
    REFERENCES TIPO_PLATO (tp_plt_id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    );
