-- MySQL Script generated by MySQL Workbench
-- Sat Aug 28 19:38:16 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema reto4
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema reto4
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `reto4` DEFAULT CHARACTER SET utf8 ;
USE `reto4` ;

-- -----------------------------------------------------
-- Table `reto4`.`TIPO_PLATO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reto4`.`TIPO_PLATO` (
  `tp_plt_id` INT NOT NULL,
  `tp_plt_nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`tp_plt_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reto4`.`PLATO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reto4`.`PLATO` (
  `plt_id` INT NOT NULL,
  `plt_nombre` VARCHAR(200) NULL,
  `plt_precio` INT NULL,
  `plt_descripcion` VARCHAR(300) NULL,
  `TIPO_PLATO_tp_plt_id` INT NOT NULL,
  PRIMARY KEY (`plt_id`),
  INDEX `fk_PLATO_TIPO_PLATO1_idx` (`TIPO_PLATO_tp_plt_id` ASC) VISIBLE,
  CONSTRAINT `fk_PLATO_TIPO_PLATO1`
    FOREIGN KEY (`TIPO_PLATO_tp_plt_id`)
    REFERENCES `reto4`.`TIPO_PLATO` (`tp_plt_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reto4`.`MESERO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reto4`.`MESERO` (
  `mes_id` INT NOT NULL,
  `mes_nombre` VARCHAR(200) NULL,
  `mes_apellidos` VARCHAR(200) NULL,
  `mes_documento` BIGINT(40) NULL,
  `mes_correo` VARCHAR(100) NULL,
  `mes_telefono` BIGINT(40) NULL,
  PRIMARY KEY (`mes_id`))
ENGINE = InnoDB
COMMENT = '	\n				';


-- -----------------------------------------------------
-- Table `reto4`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reto4`.`CLIENTE` (
  `cli_id` INT NOT NULL,
  `cli_nombres` VARCHAR(100) NULL,
  `cli_apellidos` VARCHAR(100) NULL,
  `cli_documento` BIGINT(40) NULL,
  `cli_telefono` BIGINT(40) NULL,
  PRIMARY KEY (`cli_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reto4`.`ORDEN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reto4`.`ORDEN` (
  `ordn_id` INT NOT NULL,
  `ordn_fecha` DATE NULL,
  `PLATO_plt_id` INT NOT NULL,
  `MESERO_mes_id` INT NOT NULL,
  `CLIENTE_cli_id` INT NOT NULL,
  PRIMARY KEY (`ordn_id`, `PLATO_plt_id`, `MESERO_mes_id`),
  INDEX `fk_ORDEN_PLATO1_idx` (`PLATO_plt_id` ASC) VISIBLE,
  INDEX `fk_ORDEN_MESERO1_idx` (`MESERO_mes_id` ASC) VISIBLE,
  INDEX `fk_ORDEN_CLIENTE1_idx` (`CLIENTE_cli_id` ASC) VISIBLE,
  CONSTRAINT `fk_ORDEN_PLATO1`
    FOREIGN KEY (`PLATO_plt_id`)
    REFERENCES `reto4`.`PLATO` (`plt_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ORDEN_MESERO1`
    FOREIGN KEY (`MESERO_mes_id`)
    REFERENCES `reto4`.`MESERO` (`mes_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ORDEN_CLIENTE1`
    FOREIGN KEY (`CLIENTE_cli_id`)
    REFERENCES `reto4`.`CLIENTE` (`cli_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
