-- MySQL Script generated by MySQL Workbench
-- Fri Aug 27 16:16:33 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Libreria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Libreria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Libreria` DEFAULT CHARACTER SET utf8 ;
USE `Libreria` ;

-- -----------------------------------------------------
-- Table `Libreria`.`EDITORIAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Libreria`.`EDITORIAL` (
  `edi_nombre` VARCHAR(300) NOT NULL,
  `edi_telefono` VARCHAR(20) NULL,
  `edi_ciudad` VARCHAR(100) NULL,
  `edi_pais` VARCHAR(100) NULL,
  PRIMARY KEY (`edi_nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Libreria`.`LIBRO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Libreria`.`LIBRO` (
  `lib_ISB` BIGINT(20) NOT NULL,
  `lib_titulo` VARCHAR(300) NOT NULL,
  `lib_numeropaginas` INT NOT NULL,
  `lib_year` INT NOT NULL,
  `EDITORIAL_edi_nombre` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`lib_ISB`),
  INDEX `fk_LIBRO_EDITORIAL_idx` (`EDITORIAL_edi_nombre` ASC) VISIBLE,
  CONSTRAINT `fk_LIBRO_EDITORIAL`
    FOREIGN KEY (`EDITORIAL_edi_nombre`)
    REFERENCES `Libreria`.`EDITORIAL` (`edi_nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Libreria`.`AUTOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Libreria`.`AUTOR` (
  `aut_codigo` INT NOT NULL,
  `aut_nombre` VARCHAR(200) NOT NULL,
  `aut_apellido` VARCHAR(200) NOT NULL,
  `aut_nacionalidad` VARCHAR(200) NOT NULL,
  `aut_fecha_nto` DATE NOT NULL,
  `AUTORcol` VARCHAR(45) NOT NULL,
  `fecha_compra` DATE NULL,
  PRIMARY KEY (`aut_codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Libreria`.`AUTORIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Libreria`.`AUTORIA` (
  `AUTOR_aut_codigo` INT NOT NULL,
  `LIBRO_lib_ISB` BIGINT(20) NOT NULL,
  PRIMARY KEY (`AUTOR_aut_codigo`, `LIBRO_lib_ISB`),
  INDEX `fk_AUTOR_has_LIBRO_LIBRO1_idx` (`LIBRO_lib_ISB` ASC) VISIBLE,
  INDEX `fk_AUTOR_has_LIBRO_AUTOR1_idx` (`AUTOR_aut_codigo` ASC) VISIBLE,
  CONSTRAINT `fk_AUTOR_has_LIBRO_AUTOR1`
    FOREIGN KEY (`AUTOR_aut_codigo`)
    REFERENCES `Libreria`.`AUTOR` (`aut_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AUTOR_has_LIBRO_LIBRO1`
    FOREIGN KEY (`LIBRO_lib_ISB`)
    REFERENCES `Libreria`.`LIBRO` (`lib_ISB`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Libreria`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Libreria`.`CLIENTE` (
  `cli_id` INT NOT NULL,
  `cli_nombre` VARCHAR(200) NULL,
  `cli_ciudad` VARCHAR(200) NULL,
  `cli_pais` VARCHAR(200) NULL,
  `cli_teliefono` VARCHAR(20) NULL,
  PRIMARY KEY (`cli_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Libreria`.`COMPRA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Libreria`.`COMPRA` (
  `CLIENTE_cli_id` INT NOT NULL,
  `LIBRO_lib_ISB` BIGINT(20) NOT NULL,
  PRIMARY KEY (`CLIENTE_cli_id`, `LIBRO_lib_ISB`),
  INDEX `fk_CLIENTE_has_LIBRO_LIBRO1_idx` (`LIBRO_lib_ISB` ASC) VISIBLE,
  INDEX `fk_CLIENTE_has_LIBRO_CLIENTE1_idx` (`CLIENTE_cli_id` ASC) VISIBLE,
  CONSTRAINT `fk_CLIENTE_has_LIBRO_CLIENTE1`
    FOREIGN KEY (`CLIENTE_cli_id`)
    REFERENCES `Libreria`.`CLIENTE` (`cli_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CLIENTE_has_LIBRO_LIBRO1`
    FOREIGN KEY (`LIBRO_lib_ISB`)
    REFERENCES `Libreria`.`LIBRO` (`lib_ISB`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
